services:
  - type: web
    name: UChicago-ResHall-Duty-Schedule
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 5000
